### ISSUE TITLE
Option to change commit message

### ISSUE THREAD

**Issue by Verbalinsurection** [satackey/push-prebuilt-action#2]
Hello,

Thanks for this action :)

To avoid CI to generate error, can you add the capacity to amend commit message to add string like "[ci skip]" please ?

Thanks

**Comment by satackey** [comment]
OK. I would like to add a `commit-message` to the inputs.

**Comment by satackey** [comment]
I created an action in #4 that can change the commit message.

Please let me know if this is okay. I'll merge it into the master.

**Comment by Verbalinsurection** [comment]
Hello,
Thanks for this, it's work like a charm :)
